`timescale 1ns/1ps
// Generated by Cadence Genus(TM) Synthesis Solution 21.16-s062_1
// Generated on: Feb 27 2026 06:23:57 KST (Feb 26 2026 21:23:57 UTC)

// Verification Directory fv/AXI_writer 

module AXI_writer(pclk, clk_100Mhz, rst, mixed_data, pixel_valid,
     frame_done, FRAME_BASE_ADDR, AWADDR, AWVALID, AWREADY, AWLEN,
     AWSIZE, AWBURST, AWCACHE, AWPROT, WDATA, WVALID, WREADY, WLAST,
     WSTRB, BVALID, BREADY, BRESP, o_prog_full, state, ADDR_OFFSET);
  input pclk, clk_100Mhz, rst, pixel_valid, frame_done, AWREADY,
       WREADY, BVALID;
  input [15:0] mixed_data;
  input [31:0] FRAME_BASE_ADDR;
  input [1:0] BRESP;
  output [31:0] AWADDR, ADDR_OFFSET;
  output AWVALID, WVALID, WLAST, BREADY, o_prog_full;
  output [7:0] AWLEN, WSTRB;
  output [2:0] AWSIZE, AWPROT;
  output [1:0] AWBURST, state;
  output [3:0] AWCACHE;
  output [63:0] WDATA;
  wire pclk, clk_100Mhz, rst, pixel_valid, frame_done, AWREADY, WREADY,
       BVALID;
  wire [15:0] mixed_data;
  wire [31:0] FRAME_BASE_ADDR;
  wire [1:0] BRESP;
  wire [31:0] AWADDR, ADDR_OFFSET;
  wire AWVALID, WVALID, WLAST, BREADY, o_prog_full;
  wire [7:0] AWLEN, WSTRB;
  wire [2:0] AWSIZE, AWPROT;
  wire [1:0] AWBURST, state;
  wire [3:0] AWCACHE;
  wire [63:0] WDATA;
  wire [12:0] rd_data_count;
  wire [7:0] data_count;
  wire ADD_UNS_OP_n_1, ADD_UNS_OP_n_3, ADD_UNS_OP_n_5, ADD_UNS_OP_n_7,
       ADD_UNS_OP_n_9, ADD_UNS_OP_n_11, ADD_UNS_OP_n_13,
       ADD_UNS_OP_n_15;
  wire ADD_UNS_OP_n_17, ADD_UNS_OP_n_19, ADD_UNS_OP_n_22,
       ADD_UNS_OP_n_23, ADD_UNS_OP_n_25, ADD_UNS_OP_n_27,
       ADD_UNS_OP_n_29, ADD_UNS_OP_n_31;
  wire ADD_UNS_OP_n_33, ADD_UNS_OP_n_35, ADD_UNS_OP_n_37,
       ADD_UNS_OP_n_39, ADD_UNS_OP_n_41, ADD_UNS_OP_n_43,
       ADD_UNS_OP_n_45, ADD_UNS_OP_n_47;
  wire fifo_empty, fifo_full, fifo_rd_en, frame_done_d1, frame_done_d2,
       n_0, n_1, n_2;
  wire n_3, n_4, n_5, n_6, n_7, n_8, n_9, n_10;
  wire n_11, n_12, n_13, n_14, n_15, n_16, n_17, n_18;
  wire n_19, n_20, n_21, n_22, n_23, n_24, n_25, n_26;
  wire n_27, n_28, n_29, n_30, n_31, n_32, n_33, n_34;
  wire n_35, n_36, n_37, n_38, n_39, n_40, n_41, n_42;
  wire n_43, n_44, n_45, n_46, n_47, n_48, n_49, n_50;
  wire n_51, n_52, n_53, n_54, n_55, n_56, n_57, n_58;
  wire n_59, n_60, n_61, n_62, n_63, n_64, n_65, n_66;
  wire n_67, n_68, n_69, n_70, n_71, n_72, n_73, n_74;
  wire n_75, n_76, n_77, n_78, n_79, n_80, n_81, n_82;
  wire n_83, n_84, n_85, n_86, n_87, n_88, n_89, n_90;
  wire n_91, n_92, n_93, n_97, n_98, n_99, n_100, n_101;
  wire n_102, n_103, n_104, n_105, n_106, n_107, n_108, n_109;
  wire n_110, n_111, n_112, n_113, n_114, n_115, n_116, n_117;
  wire n_118, n_119, n_120, n_121, n_122, n_123, n_124, n_125;
  wire n_126, n_127, n_128, n_129, n_130, n_131, n_132, n_133;
  wire n_153;
  assign ADDR_OFFSET[0] = 1'b0;
  assign ADDR_OFFSET[1] = 1'b0;
  assign ADDR_OFFSET[2] = 1'b0;
  assign ADDR_OFFSET[3] = 1'b0;
  assign ADDR_OFFSET[4] = 1'b0;
  assign ADDR_OFFSET[5] = 1'b0;
  assign ADDR_OFFSET[6] = 1'b0;
  assign ADDR_OFFSET[18] = 1'b0;
  assign ADDR_OFFSET[19] = 1'b0;
  assign ADDR_OFFSET[20] = 1'b0;
  assign ADDR_OFFSET[21] = 1'b0;
  assign ADDR_OFFSET[22] = 1'b0;
  assign ADDR_OFFSET[23] = 1'b0;
  assign ADDR_OFFSET[24] = 1'b0;
  assign ADDR_OFFSET[25] = 1'b0;
  assign ADDR_OFFSET[26] = 1'b0;
  assign ADDR_OFFSET[27] = 1'b0;
  assign ADDR_OFFSET[28] = 1'b0;
  assign ADDR_OFFSET[29] = 1'b0;
  assign ADDR_OFFSET[30] = 1'b0;
  assign ADDR_OFFSET[31] = 1'b0;
  assign BREADY = 1'b1;
  assign WSTRB[0] = 1'b1;
  assign WSTRB[1] = 1'b1;
  assign WSTRB[2] = 1'b1;
  assign WSTRB[3] = 1'b1;
  assign WSTRB[4] = 1'b1;
  assign WSTRB[5] = 1'b1;
  assign WSTRB[6] = 1'b1;
  assign WSTRB[7] = 1'b1;
  assign AWPROT[0] = 1'b0;
  assign AWPROT[1] = 1'b0;
  assign AWPROT[2] = 1'b0;
  assign AWCACHE[0] = 1'b0;
  assign AWCACHE[1] = 1'b1;
  assign AWCACHE[2] = 1'b0;
  assign AWCACHE[3] = 1'b0;
  assign AWBURST[0] = 1'b1;
  assign AWBURST[1] = 1'b0;
  assign AWSIZE[0] = 1'b1;
  assign AWSIZE[1] = 1'b1;
  assign AWSIZE[2] = 1'b0;
  assign AWLEN[0] = 1'b1;
  assign AWLEN[1] = 1'b1;
  assign AWLEN[2] = 1'b1;
  assign AWLEN[3] = 1'b1;
  assign AWLEN[4] = 1'b0;
  assign AWLEN[5] = 1'b0;
  assign AWLEN[6] = 1'b0;
  assign AWLEN[7] = 1'b0;
  async_fifo_DATA_WIDTH64_ADDR_WIDTH8 u_fifo_writer(.rst (n_153),
       .wr_clk (pclk), .wr_en (pixel_valid), .din ({48'b0,
       mixed_data}), .full (fifo_full), .prog_full (o_prog_full),
       .rd_clk (clk_100Mhz), .rd_en (fifo_rd_en), .dout (WDATA), .empty
       (fifo_empty), .rd_data_count (rd_data_count[8:0]));
  OR2X1 g3826__2398(.A (frame_done_d2), .B (rst), .Y (n_153));
  DFFHQX1 frame_done_d2_reg(.CK (clk_100Mhz), .D (frame_done_d1), .Q
       (frame_done_d2));
  NOR2X1 g3828__5107(.A (n_93), .B (n_97), .Y (fifo_rd_en));
  NOR2BX1 g3829__6260(.AN (ADDR_OFFSET[17]), .B (rst), .Y (n_108));
  NOR2BX1 g3830__4319(.AN (ADDR_OFFSET[14]), .B (rst), .Y (n_105));
  NAND2X1 g3831__8428(.A (WREADY), .B (WVALID), .Y (n_93));
  NOR2BX1 g3832__5526(.AN (ADDR_OFFSET[13]), .B (rst), .Y (n_104));
  DFFQXL frame_done_d1_reg(.CK (clk_100Mhz), .D (frame_done), .Q
       (frame_done_d1));
  NOR2BX1 g3834__6783(.AN (ADDR_OFFSET[12]), .B (rst), .Y (n_103));
  NAND2BX1 g3835__3680(.AN (state[0]), .B (state[1]), .Y (n_97));
  NOR2BX1 g3836__1617(.AN (ADDR_OFFSET[7]), .B (rst), .Y (n_98));
  NOR2BX1 g3837__2802(.AN (ADDR_OFFSET[16]), .B (rst), .Y (n_107));
  NOR2BX1 g3838__1705(.AN (ADDR_OFFSET[10]), .B (rst), .Y (n_101));
  NOR2BX1 g3839__5122(.AN (ADDR_OFFSET[9]), .B (rst), .Y (n_100));
  NOR2BX1 g3840__8246(.AN (ADDR_OFFSET[15]), .B (rst), .Y (n_106));
  NOR2BX1 g3841__7098(.AN (ADDR_OFFSET[8]), .B (rst), .Y (n_99));
  NOR2BX1 g3842__6131(.AN (ADDR_OFFSET[11]), .B (rst), .Y (n_102));
  SDFFQX1 \ADDR_OFFSET_reg[7] (.CK (clk_100Mhz), .D (n_66), .SI (n_68),
       .SE (ADDR_OFFSET[7]), .Q (ADDR_OFFSET[7]));
  DFFHQX1 \ADDR_OFFSET_reg[8] (.CK (clk_100Mhz), .D (n_91), .Q
       (ADDR_OFFSET[8]));
  DFFHQX1 \ADDR_OFFSET_reg[9] (.CK (clk_100Mhz), .D (n_84), .Q
       (ADDR_OFFSET[9]));
  DFFHQX1 \ADDR_OFFSET_reg[10] (.CK (clk_100Mhz), .D (n_90), .Q
       (ADDR_OFFSET[10]));
  DFFHQX1 \ADDR_OFFSET_reg[11] (.CK (clk_100Mhz), .D (n_83), .Q
       (ADDR_OFFSET[11]));
  DFFHQX1 \ADDR_OFFSET_reg[12] (.CK (clk_100Mhz), .D (n_92), .Q
       (ADDR_OFFSET[12]));
  DFFHQX1 \ADDR_OFFSET_reg[13] (.CK (clk_100Mhz), .D (n_88), .Q
       (ADDR_OFFSET[13]));
  DFFHQX1 \ADDR_OFFSET_reg[14] (.CK (clk_100Mhz), .D (n_87), .Q
       (ADDR_OFFSET[14]));
  DFFHQX1 \ADDR_OFFSET_reg[15] (.CK (clk_100Mhz), .D (n_86), .Q
       (ADDR_OFFSET[15]));
  DFFHQX1 \ADDR_OFFSET_reg[16] (.CK (clk_100Mhz), .D (n_85), .Q
       (ADDR_OFFSET[16]));
  DFFHQX1 \ADDR_OFFSET_reg[17] (.CK (clk_100Mhz), .D (n_78), .Q
       (ADDR_OFFSET[17]));
  SDFFQX1 \AWADDR_reg[0] (.CK (clk_100Mhz), .D (AWADDR[0]), .SI
       (FRAME_BASE_ADDR[0]), .SE (n_32), .Q (AWADDR[0]));
  SDFFQX1 \AWADDR_reg[1] (.CK (clk_100Mhz), .D (AWADDR[1]), .SI
       (FRAME_BASE_ADDR[1]), .SE (n_32), .Q (AWADDR[1]));
  SDFFQX1 \AWADDR_reg[2] (.CK (clk_100Mhz), .D (AWADDR[2]), .SI
       (FRAME_BASE_ADDR[2]), .SE (n_32), .Q (AWADDR[2]));
  SDFFQX1 \AWADDR_reg[3] (.CK (clk_100Mhz), .D (AWADDR[3]), .SI
       (FRAME_BASE_ADDR[3]), .SE (n_32), .Q (AWADDR[3]));
  SDFFQX1 \AWADDR_reg[4] (.CK (clk_100Mhz), .D (AWADDR[4]), .SI
       (FRAME_BASE_ADDR[4]), .SE (n_32), .Q (AWADDR[4]));
  SDFFQX1 \AWADDR_reg[5] (.CK (clk_100Mhz), .D (AWADDR[5]), .SI
       (FRAME_BASE_ADDR[5]), .SE (n_32), .Q (AWADDR[5]));
  SDFFQX1 \AWADDR_reg[6] (.CK (clk_100Mhz), .D (AWADDR[6]), .SI
       (FRAME_BASE_ADDR[6]), .SE (n_32), .Q (AWADDR[6]));
  SDFFQX1 \AWADDR_reg[7] (.CK (clk_100Mhz), .D (AWADDR[7]), .SI
       (n_133), .SE (n_32), .Q (AWADDR[7]));
  SDFFQX1 \AWADDR_reg[8] (.CK (clk_100Mhz), .D (AWADDR[8]), .SI
       (n_132), .SE (n_32), .Q (AWADDR[8]));
  SDFFQX1 \AWADDR_reg[9] (.CK (clk_100Mhz), .D (AWADDR[9]), .SI
       (n_131), .SE (n_32), .Q (AWADDR[9]));
  SDFFQX1 \AWADDR_reg[10] (.CK (clk_100Mhz), .D (AWADDR[10]), .SI
       (n_130), .SE (n_32), .Q (AWADDR[10]));
  SDFFQX1 \AWADDR_reg[11] (.CK (clk_100Mhz), .D (AWADDR[11]), .SI
       (n_129), .SE (n_32), .Q (AWADDR[11]));
  SDFFQX1 \AWADDR_reg[12] (.CK (clk_100Mhz), .D (AWADDR[12]), .SI
       (n_128), .SE (n_32), .Q (AWADDR[12]));
  SDFFQX1 \AWADDR_reg[13] (.CK (clk_100Mhz), .D (AWADDR[13]), .SI
       (n_127), .SE (n_32), .Q (AWADDR[13]));
  SDFFQX1 \AWADDR_reg[14] (.CK (clk_100Mhz), .D (AWADDR[14]), .SI
       (n_126), .SE (n_32), .Q (AWADDR[14]));
  SDFFQX1 \AWADDR_reg[15] (.CK (clk_100Mhz), .D (AWADDR[15]), .SI
       (n_125), .SE (n_32), .Q (AWADDR[15]));
  SDFFQX1 \AWADDR_reg[16] (.CK (clk_100Mhz), .D (AWADDR[16]), .SI
       (n_124), .SE (n_32), .Q (AWADDR[16]));
  SDFFQX1 \AWADDR_reg[17] (.CK (clk_100Mhz), .D (AWADDR[17]), .SI
       (n_123), .SE (n_32), .Q (AWADDR[17]));
  SDFFQX1 \AWADDR_reg[18] (.CK (clk_100Mhz), .D (AWADDR[18]), .SI
       (n_122), .SE (n_32), .Q (AWADDR[18]));
  SDFFQX1 \AWADDR_reg[19] (.CK (clk_100Mhz), .D (AWADDR[19]), .SI
       (n_121), .SE (n_32), .Q (AWADDR[19]));
  SDFFQX1 \AWADDR_reg[20] (.CK (clk_100Mhz), .D (AWADDR[20]), .SI
       (n_120), .SE (n_32), .Q (AWADDR[20]));
  SDFFQX1 \AWADDR_reg[21] (.CK (clk_100Mhz), .D (AWADDR[21]), .SI
       (n_119), .SE (n_32), .Q (AWADDR[21]));
  SDFFQX1 \AWADDR_reg[22] (.CK (clk_100Mhz), .D (AWADDR[22]), .SI
       (n_118), .SE (n_32), .Q (AWADDR[22]));
  SDFFQX1 \AWADDR_reg[23] (.CK (clk_100Mhz), .D (AWADDR[23]), .SI
       (n_117), .SE (n_32), .Q (AWADDR[23]));
  SDFFQX1 \AWADDR_reg[24] (.CK (clk_100Mhz), .D (AWADDR[24]), .SI
       (n_116), .SE (n_32), .Q (AWADDR[24]));
  SDFFQX1 \AWADDR_reg[25] (.CK (clk_100Mhz), .D (AWADDR[25]), .SI
       (n_115), .SE (n_32), .Q (AWADDR[25]));
  SDFFQX1 \AWADDR_reg[26] (.CK (clk_100Mhz), .D (AWADDR[26]), .SI
       (n_114), .SE (n_32), .Q (AWADDR[26]));
  SDFFQX1 \AWADDR_reg[27] (.CK (clk_100Mhz), .D (AWADDR[27]), .SI
       (n_113), .SE (n_32), .Q (AWADDR[27]));
  SDFFQX1 \AWADDR_reg[28] (.CK (clk_100Mhz), .D (AWADDR[28]), .SI
       (n_112), .SE (n_32), .Q (AWADDR[28]));
  SDFFQX1 \AWADDR_reg[29] (.CK (clk_100Mhz), .D (AWADDR[29]), .SI
       (n_111), .SE (n_32), .Q (AWADDR[29]));
  SDFFQX1 \AWADDR_reg[30] (.CK (clk_100Mhz), .D (AWADDR[30]), .SI
       (n_110), .SE (n_32), .Q (AWADDR[30]));
  SDFFQX1 \AWADDR_reg[31] (.CK (clk_100Mhz), .D (AWADDR[31]), .SI
       (n_109), .SE (n_32), .Q (AWADDR[31]));
  DFFHQX1 AWVALID_reg(.CK (clk_100Mhz), .D (n_49), .Q (AWVALID));
  SDFFQX1 WLAST_reg(.CK (clk_100Mhz), .D (WLAST), .SI (n_38), .SE
       (n_44), .Q (WLAST));
  DFFHQX1 WVALID_reg(.CK (clk_100Mhz), .D (n_62), .Q (WVALID));
  DFFHQX1 \data_count_reg[0] (.CK (clk_100Mhz), .D (n_46), .Q
       (data_count[0]));
  DFFHQX1 \data_count_reg[1] (.CK (clk_100Mhz), .D (n_53), .Q
       (data_count[1]));
  DFFHQX1 \data_count_reg[2] (.CK (clk_100Mhz), .D (n_54), .Q
       (data_count[2]));
  DFFHQX1 \data_count_reg[3] (.CK (clk_100Mhz), .D (n_55), .Q
       (data_count[3]));
  DFFHQX1 \state_reg[0] (.CK (clk_100Mhz), .D (n_58), .Q (state[0]));
  SDFFQX1 \state_reg[1] (.CK (clk_100Mhz), .D (n_26), .SI (n_23), .SE
       (state[1]), .Q (state[1]));
  NOR2X1 g4932__1881(.A (n_153), .B (n_89), .Y (n_92));
  NOR2X1 g4937__5115(.A (n_153), .B (n_75), .Y (n_91));
  OAI31X1 g4938__7482(.A0 (ADDR_OFFSET[10]), .A1 (n_28), .A2 (n_67),
       .B0 (n_80), .Y (n_90));
  XNOR2X1 g4939__4733(.A (ADDR_OFFSET[12]), .B (n_70), .Y (n_89));
  OAI31X1 g4942__6161(.A0 (ADDR_OFFSET[13]), .A1 (n_43), .A2 (n_67),
       .B0 (n_81), .Y (n_88));
  OAI31X1 g4943__9315(.A0 (ADDR_OFFSET[14]), .A1 (n_48), .A2 (n_67),
       .B0 (n_82), .Y (n_87));
  OAI31X1 g4944__9945(.A0 (ADDR_OFFSET[15]), .A1 (n_56), .A2 (n_67),
       .B0 (n_79), .Y (n_86));
  OAI31X1 g4945__2883(.A0 (ADDR_OFFSET[16]), .A1 (n_60), .A2 (n_67),
       .B0 (n_76), .Y (n_85));
  OAI31X1 g4946__2346(.A0 (ADDR_OFFSET[9]), .A1 (n_16), .A2 (n_67), .B0
       (n_77), .Y (n_84));
  OAI32X1 g4947__1666(.A0 (ADDR_OFFSET[11]), .A1 (n_35), .A2 (n_67),
       .B0 (n_6), .B1 (n_74), .Y (n_83));
  OAI21XL g4948__7410(.A0 (n_50), .A1 (n_68), .B0 (ADDR_OFFSET[14]), .Y
       (n_82));
  NAND2X1 g4949__6417(.A (ADDR_OFFSET[13]), .B (n_73), .Y (n_81));
  OAI21XL g4950__5477(.A0 (n_30), .A1 (n_68), .B0 (ADDR_OFFSET[10]), .Y
       (n_80));
  NAND2X1 g4951__2398(.A (ADDR_OFFSET[15]), .B (n_72), .Y (n_79));
  OAI32X1 g4952__5107(.A0 (n_1), .A1 (n_60), .A2 (n_67), .B0 (n_153),
       .B1 (n_4), .Y (n_78));
  NAND2X1 g4953__6260(.A (ADDR_OFFSET[9]), .B (n_71), .Y (n_77));
  OAI21XL g4954__4319(.A0 (n_61), .A1 (n_68), .B0 (ADDR_OFFSET[16]), .Y
       (n_76));
  XNOR2X1 g4955__8428(.A (ADDR_OFFSET[8]), .B (n_65), .Y (n_75));
  AOI21X1 g4956__5526(.A0 (n_0), .A1 (n_35), .B0 (n_68), .Y (n_74));
  OAI2BB1X1 g4957__6783(.A0N (n_0), .A1N (n_43), .B0 (n_69), .Y (n_73));
  OAI2BB1X1 g4958__3680(.A0N (n_0), .A1N (n_56), .B0 (n_69), .Y (n_72));
  OAI2BB1X1 g4959__1617(.A0N (n_0), .A1N (n_16), .B0 (n_69), .Y (n_71));
  NOR3X1 g4960__2802(.A (n_6), .B (n_35), .C (n_64), .Y (n_70));
  INVX1 g4961(.A (n_69), .Y (n_68));
  NAND2X1 g4962__1705(.A (n_0), .B (n_64), .Y (n_69));
  INVXL g4963(.A (n_67), .Y (n_66));
  NOR2BX1 g4964__5122(.AN (ADDR_OFFSET[7]), .B (n_64), .Y (n_65));
  OR2X1 g4965__8246(.A (n_153), .B (n_64), .Y (n_67));
  NAND4X1 g4966__7098(.A (BVALID), .B (state[0]), .C (state[1]), .D
       (n_63), .Y (n_64));
  OAI31X1 g4967__6131(.A0 (ADDR_OFFSET[16]), .A1 (ADDR_OFFSET[15]), .A2
       (n_59), .B0 (ADDR_OFFSET[17]), .Y (n_63));
  NOR2XL g4971__1881(.A (n_57), .B (rst), .Y (n_62));
  AND2XL g4972__5115(.A (n_0), .B (n_60), .Y (n_61));
  OA21X1 g4977__7482(.A0 (ADDR_OFFSET[13]), .A1 (n_45), .B0
       (ADDR_OFFSET[14]), .Y (n_59));
  OAI221X1 g4978__4733(.A0 (state[1]), .A1 (n_42), .B0 (n_14), .B1
       (n_29), .C0 (n_51), .Y (n_58));
  AOI21XL g4979__6161(.A0 (WVALID), .A1 (n_18), .B0 (n_52), .Y (n_57));
  NAND2BX1 g4980__9315(.AN (n_56), .B (ADDR_OFFSET[15]), .Y (n_60));
  OAI32X1 g5001__9945(.A0 (data_count[3]), .A1 (n_27), .A2 (n_36), .B0
       (n_3), .B1 (n_41), .Y (n_55));
  OAI32X1 g5002__2883(.A0 (data_count[2]), .A1 (n_17), .A2 (n_36), .B0
       (n_9), .B1 (n_40), .Y (n_54));
  OAI31X1 g5003__2346(.A0 (data_count[1]), .A1 (n_7), .A2 (n_36), .B0
       (n_47), .Y (n_53));
  AOI211XL g5004__1666(.A0 (fifo_rd_en), .A1 (n_37), .B0
       (frame_done_d2), .C0 (n_18), .Y (n_52));
  NAND4BX1 g5005__7410(.AN (n_38), .B (WREADY), .C (state[1]), .D
       (n_12), .Y (n_51));
  AND2XL g5006__6417(.A (n_0), .B (n_48), .Y (n_50));
  AOI21XL g5007__5477(.A0 (n_25), .A1 (n_39), .B0 (rst), .Y (n_49));
  NAND2BX1 g5021__2398(.AN (n_48), .B (ADDR_OFFSET[14]), .Y (n_56));
  OAI21X1 g5022__5107(.A0 (n_34), .A1 (n_33), .B0 (data_count[1]), .Y
       (n_47));
  NAND2BX1 g5023__6260(.AN (n_43), .B (ADDR_OFFSET[13]), .Y (n_48));
  OAI32X1 g5025__4319(.A0 (n_153), .A1 (n_7), .A2 (n_21), .B0
       (data_count[0]), .B1 (n_36), .Y (n_46));
  AOI21X1 g5026__8428(.A0 (n_6), .A1 (n_35), .B0 (n_8), .Y (n_45));
  NOR3X1 g5027__5526(.A (n_153), .B (n_97), .C (n_31), .Y (n_44));
  OAI31X1 g5028__6783(.A0 (rd_data_count[5]), .A1 (rd_data_count[6]),
       .A2 (n_20), .B0 (n_12), .Y (n_42));
  NAND3BXL g5029__3680(.AN (n_35), .B (ADDR_OFFSET[12]), .C
       (ADDR_OFFSET[11]), .Y (n_43));
  AOI21X1 g5030__1617(.A0 (n_27), .A1 (n_24), .B0 (n_33), .Y (n_41));
  AOI21X1 g5031__2802(.A0 (n_17), .A1 (n_24), .B0 (n_33), .Y (n_40));
  NAND4XL g5032__1705(.A (n_2), .B (state[0]), .C (n_15), .D (n_19), .Y
       (n_39));
  INVXL g5033(.A (n_38), .Y (n_37));
  NOR2BX1 g5034__5122(.AN (n_24), .B (data_count[0]), .Y (n_34));
  OR2XL g5035__8246(.A (n_3), .B (n_27), .Y (n_38));
  NAND2X1 g5036__7098(.A (n_24), .B (n_13), .Y (n_36));
  NAND2BX1 g5037__6131(.AN (n_28), .B (ADDR_OFFSET[10]), .Y (n_35));
  NAND4XL g5038__1881(.A (data_count[1]), .B (data_count[2]), .C
       (data_count[3]), .D (fifo_rd_en), .Y (n_31));
  NOR2BX1 g5039__5115(.AN (n_28), .B (n_153), .Y (n_30));
  AOI22X1 g5040__7482(.A0 (n_5), .A1 (n_15), .B0 (n_10), .B1
       (state[1]), .Y (n_29));
  OAI21X1 g5041__4733(.A0 (n_11), .A1 (n_13), .B0 (n_14), .Y (n_33));
  OR2X2 g5042__6161(.A (n_22), .B (rst), .Y (n_32));
  NOR2XL g5043__9315(.A (n_14), .B (n_15), .Y (n_26));
  NAND2BX1 g5044__9945(.AN (n_19), .B (AWVALID), .Y (n_25));
  NAND2BX1 g5045__2883(.AN (n_16), .B (ADDR_OFFSET[9]), .Y (n_28));
  OR2X1 g5046__2346(.A (n_9), .B (n_17), .Y (n_27));
  OAI2BB1X1 g5047__1666(.A0N (n_0), .A1N (n_10), .B0 (n_11), .Y (n_23));
  NOR3XL g5048__7410(.A (frame_done_d2), .B (state[0]), .C (state[1]),
       .Y (n_22));
  NOR2BX1 g5049__6417(.AN (n_13), .B (state[0]), .Y (n_21));
  OR3X1 g5050__5477(.A (rd_data_count[7]), .B (rd_data_count[8]), .C
       (rd_data_count[4]), .Y (n_20));
  NOR2X1 g5051__2398(.A (n_97), .B (n_11), .Y (n_24));
  NAND2XL g5052__5107(.A (n_2), .B (state[1]), .Y (n_19));
  AND2X1 g5053__6260(.A (n_97), .B (n_2), .Y (n_18));
  NAND2X1 g5054__4319(.A (data_count[1]), .B (data_count[0]), .Y
       (n_17));
  NAND2X1 g5055__8428(.A (ADDR_OFFSET[8]), .B (ADDR_OFFSET[7]), .Y
       (n_16));
  INVX1 g5056(.A (n_12), .Y (n_11));
  NAND2X1 g5057__5526(.A (AWREADY), .B (AWVALID), .Y (n_15));
  NAND2X1 g5058__6783(.A (n_0), .B (state[0]), .Y (n_14));
  OR2X1 g5059__3680(.A (n_5), .B (fifo_rd_en), .Y (n_13));
  NOR2X1 g5060__1617(.A (n_153), .B (state[0]), .Y (n_12));
  INVX1 g5061(.A (BVALID), .Y (n_10));
  INVX1 g5062(.A (data_count[2]), .Y (n_9));
  INVX1 g5063(.A (ADDR_OFFSET[12]), .Y (n_8));
  INVX1 g5064(.A (data_count[0]), .Y (n_7));
  INVX1 g5065(.A (ADDR_OFFSET[11]), .Y (n_6));
  INVX1 g5066(.A (state[1]), .Y (n_5));
  INVX1 g5067(.A (ADDR_OFFSET[17]), .Y (n_4));
  INVX1 g5068(.A (data_count[3]), .Y (n_3));
  INVX1 g5069(.A (frame_done_d2), .Y (n_2));
  INVX1 g5070(.A (ADDR_OFFSET[16]), .Y (n_1));
  INVX1 g5071(.A (n_153), .Y (n_0));
  XNOR2X1 ADD_UNS_OP_g517__2802(.A (FRAME_BASE_ADDR[31]), .B
       (ADD_UNS_OP_n_47), .Y (n_109));
  OA21X1 ADD_UNS_OP_g518__1705(.A0 (FRAME_BASE_ADDR[30]), .A1
       (ADD_UNS_OP_n_45), .B0 (ADD_UNS_OP_n_47), .Y (n_110));
  NAND2X1 ADD_UNS_OP_g519__5122(.A (FRAME_BASE_ADDR[30]), .B
       (ADD_UNS_OP_n_45), .Y (ADD_UNS_OP_n_47));
  AOI2BB1XL ADD_UNS_OP_g520__8246(.A0N (FRAME_BASE_ADDR[29]), .A1N
       (ADD_UNS_OP_n_43), .B0 (ADD_UNS_OP_n_45), .Y (n_111));
  AND2XL ADD_UNS_OP_g521__7098(.A (FRAME_BASE_ADDR[29]), .B
       (ADD_UNS_OP_n_43), .Y (ADD_UNS_OP_n_45));
  AOI2BB1XL ADD_UNS_OP_g522__6131(.A0N (FRAME_BASE_ADDR[28]), .A1N
       (ADD_UNS_OP_n_41), .B0 (ADD_UNS_OP_n_43), .Y (n_112));
  AND2XL ADD_UNS_OP_g523__1881(.A (FRAME_BASE_ADDR[28]), .B
       (ADD_UNS_OP_n_41), .Y (ADD_UNS_OP_n_43));
  AOI2BB1XL ADD_UNS_OP_g524__5115(.A0N (FRAME_BASE_ADDR[27]), .A1N
       (ADD_UNS_OP_n_39), .B0 (ADD_UNS_OP_n_41), .Y (n_113));
  AND2XL ADD_UNS_OP_g525__7482(.A (FRAME_BASE_ADDR[27]), .B
       (ADD_UNS_OP_n_39), .Y (ADD_UNS_OP_n_41));
  AOI2BB1XL ADD_UNS_OP_g526__4733(.A0N (FRAME_BASE_ADDR[26]), .A1N
       (ADD_UNS_OP_n_37), .B0 (ADD_UNS_OP_n_39), .Y (n_114));
  AND2XL ADD_UNS_OP_g527__6161(.A (FRAME_BASE_ADDR[26]), .B
       (ADD_UNS_OP_n_37), .Y (ADD_UNS_OP_n_39));
  AOI2BB1XL ADD_UNS_OP_g528__9315(.A0N (FRAME_BASE_ADDR[25]), .A1N
       (ADD_UNS_OP_n_35), .B0 (ADD_UNS_OP_n_37), .Y (n_115));
  AND2XL ADD_UNS_OP_g529__9945(.A (FRAME_BASE_ADDR[25]), .B
       (ADD_UNS_OP_n_35), .Y (ADD_UNS_OP_n_37));
  AOI2BB1XL ADD_UNS_OP_g530__2883(.A0N (FRAME_BASE_ADDR[24]), .A1N
       (ADD_UNS_OP_n_33), .B0 (ADD_UNS_OP_n_35), .Y (n_116));
  AND2XL ADD_UNS_OP_g531__2346(.A (FRAME_BASE_ADDR[24]), .B
       (ADD_UNS_OP_n_33), .Y (ADD_UNS_OP_n_35));
  AOI2BB1XL ADD_UNS_OP_g532__1666(.A0N (FRAME_BASE_ADDR[23]), .A1N
       (ADD_UNS_OP_n_31), .B0 (ADD_UNS_OP_n_33), .Y (n_117));
  AND2XL ADD_UNS_OP_g533__7410(.A (FRAME_BASE_ADDR[23]), .B
       (ADD_UNS_OP_n_31), .Y (ADD_UNS_OP_n_33));
  AOI2BB1XL ADD_UNS_OP_g534__6417(.A0N (FRAME_BASE_ADDR[22]), .A1N
       (ADD_UNS_OP_n_29), .B0 (ADD_UNS_OP_n_31), .Y (n_118));
  AND2XL ADD_UNS_OP_g535__5477(.A (FRAME_BASE_ADDR[22]), .B
       (ADD_UNS_OP_n_29), .Y (ADD_UNS_OP_n_31));
  AOI2BB1XL ADD_UNS_OP_g536__2398(.A0N (FRAME_BASE_ADDR[21]), .A1N
       (ADD_UNS_OP_n_27), .B0 (ADD_UNS_OP_n_29), .Y (n_119));
  AND2XL ADD_UNS_OP_g537__5107(.A (FRAME_BASE_ADDR[21]), .B
       (ADD_UNS_OP_n_27), .Y (ADD_UNS_OP_n_29));
  AOI2BB1XL ADD_UNS_OP_g538__6260(.A0N (FRAME_BASE_ADDR[20]), .A1N
       (ADD_UNS_OP_n_25), .B0 (ADD_UNS_OP_n_27), .Y (n_120));
  AND2XL ADD_UNS_OP_g539__4319(.A (FRAME_BASE_ADDR[20]), .B
       (ADD_UNS_OP_n_25), .Y (ADD_UNS_OP_n_27));
  AOI2BB1XL ADD_UNS_OP_g540__8428(.A0N (FRAME_BASE_ADDR[19]), .A1N
       (ADD_UNS_OP_n_23), .B0 (ADD_UNS_OP_n_25), .Y (n_121));
  AND2XL ADD_UNS_OP_g541__5526(.A (FRAME_BASE_ADDR[19]), .B
       (ADD_UNS_OP_n_23), .Y (ADD_UNS_OP_n_25));
  AOI2BB1XL ADD_UNS_OP_g542__6783(.A0N (FRAME_BASE_ADDR[18]), .A1N
       (ADD_UNS_OP_n_22), .B0 (ADD_UNS_OP_n_23), .Y (n_122));
  AND2XL ADD_UNS_OP_g543__3680(.A (FRAME_BASE_ADDR[18]), .B
       (ADD_UNS_OP_n_22), .Y (ADD_UNS_OP_n_23));
  ADDFX1 ADD_UNS_OP_g544__1617(.A (FRAME_BASE_ADDR[17]), .B (n_108),
       .CI (ADD_UNS_OP_n_19), .CO (ADD_UNS_OP_n_22), .S (n_123));
  ADDFX1 ADD_UNS_OP_g545__2802(.A (FRAME_BASE_ADDR[16]), .B (n_107),
       .CI (ADD_UNS_OP_n_17), .CO (ADD_UNS_OP_n_19), .S (n_124));
  ADDFX1 ADD_UNS_OP_g546__1705(.A (FRAME_BASE_ADDR[15]), .B (n_106),
       .CI (ADD_UNS_OP_n_15), .CO (ADD_UNS_OP_n_17), .S (n_125));
  ADDFX1 ADD_UNS_OP_g547__5122(.A (FRAME_BASE_ADDR[14]), .B (n_105),
       .CI (ADD_UNS_OP_n_13), .CO (ADD_UNS_OP_n_15), .S (n_126));
  ADDFX1 ADD_UNS_OP_g548__8246(.A (FRAME_BASE_ADDR[13]), .B (n_104),
       .CI (ADD_UNS_OP_n_11), .CO (ADD_UNS_OP_n_13), .S (n_127));
  ADDFX1 ADD_UNS_OP_g549__7098(.A (FRAME_BASE_ADDR[12]), .B (n_103),
       .CI (ADD_UNS_OP_n_9), .CO (ADD_UNS_OP_n_11), .S (n_128));
  ADDFX1 ADD_UNS_OP_g550__6131(.A (FRAME_BASE_ADDR[11]), .B (n_102),
       .CI (ADD_UNS_OP_n_7), .CO (ADD_UNS_OP_n_9), .S (n_129));
  ADDFX1 ADD_UNS_OP_g551__1881(.A (FRAME_BASE_ADDR[10]), .B (n_101),
       .CI (ADD_UNS_OP_n_5), .CO (ADD_UNS_OP_n_7), .S (n_130));
  ADDFX1 ADD_UNS_OP_g552__5115(.A (FRAME_BASE_ADDR[9]), .B (n_100), .CI
       (ADD_UNS_OP_n_3), .CO (ADD_UNS_OP_n_5), .S (n_131));
  ADDFX1 ADD_UNS_OP_g553__7482(.A (FRAME_BASE_ADDR[8]), .B (n_99), .CI
       (ADD_UNS_OP_n_1), .CO (ADD_UNS_OP_n_3), .S (n_132));
  AOI2BB1XL ADD_UNS_OP_g554__4733(.A0N (FRAME_BASE_ADDR[7]), .A1N
       (n_98), .B0 (ADD_UNS_OP_n_1), .Y (n_133));
  AND2XL ADD_UNS_OP_g555__6161(.A (FRAME_BASE_ADDR[7]), .B (n_98), .Y
       (ADD_UNS_OP_n_1));
endmodule

