`timescale 1ns/1ps // GLS 돌릴 때, timescale 추가해야 오류 안남.

// Generated by Cadence Genus(TM) Synthesis Solution 21.16-s062_1
// Generated on: Feb 25 2026 03:33:59 KST (Feb 24 2026 18:33:59 UTC)

// Verification Directory fv/Camera_capture 

module Camera_capture(rst, p_clock, vsync, href, p_data, pixel_data,
     frame_done, o_x_count, o_y_count, pixel_valid);
  input rst, p_clock, vsync, href;
  input [7:0] p_data;
  output [15:0] pixel_data;
  output frame_done, pixel_valid;
  output [9:0] o_x_count;
  output [8:0] o_y_count;
  wire rst, p_clock, vsync, href;
  wire [7:0] p_data;
  wire [15:0] pixel_data;
  wire frame_done, pixel_valid;
  wire [9:0] o_x_count;
  wire [8:0] o_y_count;
  wire [8:0] y_count;
  wire [9:0] x_count;
  wire [7:0] p_data_r2;
  wire [7:0] p_data_buf;
  wire [7:0] p_data_r1;
  wire href_r1, href_r2, n_0, n_2, n_3, n_4, n_5, n_6;
  wire n_7, n_8, n_9, n_10, n_11, n_12, n_13, n_14;
  wire n_15, n_16, n_17, n_18, n_19, n_20, n_21, n_22;
  wire n_23, n_24, n_25, n_26, n_27, n_28, n_29, n_30;
  wire n_31, n_32, n_34, n_35, n_36, n_37, n_38, n_39;
  wire n_40, n_41, n_42, n_43, n_44, n_45, n_46, n_47;
  wire n_48, n_49, n_50, n_51, n_52, n_53, n_54, n_55;
  wire n_56, n_57, n_58, n_59, n_60, n_61, n_62, n_63;
  wire n_64, n_65, n_66, n_67, n_68, n_69, n_70, n_71;
  wire n_72, n_73, n_74, n_75, n_76, n_77, n_78, n_79;
  wire n_80, n_81, n_82, n_83, n_84, n_85, n_86, n_87;
  wire n_88, n_89, n_90, n_91, n_92, n_93, n_94, n_95;
  wire n_96, n_97, n_98, n_99, n_100, n_101, n_102, n_103;
  wire n_104, n_105, n_106, n_107, n_108, n_109, n_110, n_111;
  wire n_112, n_113, n_114, n_115, n_116, n_117, n_119, n_120;
  wire n_121, n_123, n_124, n_125, n_126, n_127, n_128, n_129;
  wire n_130, n_131, n_133, n_134, n_135, n_136, n_137, n_138;
  wire n_139, n_140, n_141, n_142, n_143, n_144, n_145, n_146;
  wire n_147, n_148, n_149, n_150, n_151, n_152, n_153, n_154;
  wire n_155, n_156, n_157, n_158, n_159, n_160, n_161, n_162;
  wire n_163, n_164, n_165, n_166, n_167, n_168, n_169, n_170;
  wire n_171, n_172, n_173, n_174, n_176, n_177, n_178, n_179;
  wire n_180, n_181, n_182, n_183, n_184, n_185, n_199, n_200;
  wire n_201, pixel_flag, vsync_r1, vsync_r2;
  assign o_y_count[8] = 1'b0;
  assign o_x_count[9] = 1'b0;
  DFFHQX1 \y_count_reg[7] (.CK (p_clock), .D (n_185), .Q (y_count[7]));
  DFFHQX1 \y_count_reg[8] (.CK (p_clock), .D (n_184), .Q (y_count[8]));
  DFFHQX1 \y_count_reg[6] (.CK (p_clock), .D (n_183), .Q (y_count[6]));
  AND2XL g3116__2398(.A (n_174), .B (n_181), .Y (n_185));
  NOR2X1 g3117__5107(.A (n_182), .B (n_180), .Y (n_184));
  NOR2X1 g3121__6260(.A (n_178), .B (n_182), .Y (n_183));
  OAI211X1 g3120__4319(.A0 (y_count[7]), .A1 (n_176), .B0 (n_170), .C0
       (n_177), .Y (n_181));
  DFFHQX1 \x_count_reg[9] (.CK (p_clock), .D (n_179), .Q (x_count[9]));
  DFFHQX1 \y_count_reg[5] (.CK (p_clock), .D (n_199), .Q (y_count[5]));
  AOI21X1 g3119__8428(.A0 (y_count[7]), .A1 (n_172), .B0 (y_count[8]),
       .Y (n_180));
  DFFHQX1 \x_count_reg[8] (.CK (p_clock), .D (n_173), .Q (x_count[8]));
  OAI2BB1X1 g3131__5526(.A0N (x_count[9]), .A1N (n_167), .B0 (n_162),
       .Y (n_179));
  MXI2XL g3123__6783(.A (n_169), .B (n_171), .S0 (y_count[6]), .Y
       (n_178));
  DFFHQX1 \y_count_reg[4] (.CK (p_clock), .D (n_168), .Q (y_count[4]));
  NAND2X1 g3125__3680(.A (y_count[7]), .B (n_176), .Y (n_177));
  DFFQXL \x_count_d_reg[6] (.CK (p_clock), .D (n_148), .Q
       (o_x_count[6]));
  DFFQXL \x_count_d_reg[3] (.CK (p_clock), .D (n_156), .Q
       (o_x_count[3]));
  DFFQXL \x_count_d_reg[2] (.CK (p_clock), .D (n_151), .Q
       (o_x_count[2]));
  DFFQXL \x_count_d_reg[5] (.CK (p_clock), .D (n_152), .Q
       (o_x_count[5]));
  DFFQXL \x_count_d_reg[0] (.CK (p_clock), .D (n_157), .Q
       (o_x_count[0]));
  DFFQXL \x_count_d_reg[1] (.CK (p_clock), .D (n_150), .Q
       (o_x_count[1]));
  DFFQXL \x_count_d_reg[4] (.CK (p_clock), .D (n_153), .Q
       (o_x_count[4]));
  OAI32X1 g3138__2802(.A0 (x_count[8]), .A1 (n_145), .A2 (n_127), .B0
       (n_13), .B1 (n_166), .Y (n_173));
  INVX1 g3129(.A (n_176), .Y (n_172));
  DFFHQX1 \x_count_reg[3] (.CK (p_clock), .D (n_159), .Q (x_count[3]));
  DFFHQX1 \x_count_reg[2] (.CK (p_clock), .D (n_160), .Q (x_count[2]));
  DFFHQX1 \x_count_reg[4] (.CK (p_clock), .D (n_165), .Q (x_count[4]));
  DFFHQX1 \x_count_reg[5] (.CK (p_clock), .D (n_158), .Q (x_count[5]));
  DFFHQX1 \x_count_reg[6] (.CK (p_clock), .D (n_164), .Q (x_count[6]));
  NAND2XL g3130__1705(.A (n_170), .B (n_169), .Y (n_171));
  DFFHQX1 \y_count_reg[3] (.CK (p_clock), .D (n_147), .Q (y_count[3]));
  SDFFQX1 \x_count_reg[7] (.CK (p_clock), .D (n_161), .SI (n_144), .SE
       (x_count[7]), .Q (x_count[7]));
  OAI32X1 g3139__5122(.A0 (y_count[4]), .A1 (n_141), .A2 (n_146), .B0
       (n_126), .B1 (n_142), .Y (n_168));
  OAI21X1 g3144__8246(.A0 (x_count[8]), .A1 (n_128), .B0 (n_166), .Y
       (n_167));
  NAND2X1 g3132__7098(.A (y_count[6]), .B (n_169), .Y (n_176));
  OAI31X1 g3191__6131(.A0 (x_count[4]), .A1 (n_45), .A2 (n_163), .B0
       (n_134), .Y (n_165));
  OAI31X1 g3182__1881(.A0 (x_count[6]), .A1 (n_113), .A2 (n_163), .B0
       (n_201), .Y (n_164));
  NAND4XL g3186__5115(.A (x_count[8]), .B (x_count[7]), .C (n_130), .D
       (n_161), .Y (n_162));
  OAI31X1 g3188__7482(.A0 (x_count[2]), .A1 (n_0), .A2 (n_163), .B0
       (n_137), .Y (n_160));
  OAI31X1 g3189__4733(.A0 (x_count[3]), .A1 (n_119), .A2 (n_163), .B0
       (n_133), .Y (n_159));
  OAI31X1 g3190__6161(.A0 (x_count[5]), .A1 (n_123), .A2 (n_163), .B0
       (n_135), .Y (n_158));
  DFFQXL \x_count_d_reg[7] (.CK (p_clock), .D (n_139), .Q
       (o_x_count[7]));
  AO22XL g3158__9315(.A0 (o_x_count[0]), .A1 (n_155), .B0 (x_count[1]),
       .B1 (n_154), .Y (n_157));
  AO22XL g3155__9945(.A0 (o_x_count[3]), .A1 (n_155), .B0 (x_count[4]),
       .B1 (n_154), .Y (n_156));
  AO22XL g3156__2883(.A0 (o_x_count[4]), .A1 (n_155), .B0 (x_count[5]),
       .B1 (n_154), .Y (n_153));
  AO22XL g3157__2346(.A0 (o_x_count[5]), .A1 (n_155), .B0 (x_count[6]),
       .B1 (n_154), .Y (n_152));
  AO22XL g3154__1666(.A0 (o_x_count[2]), .A1 (n_155), .B0 (x_count[3]),
       .B1 (n_154), .Y (n_151));
  AO22XL g3159__7410(.A0 (o_x_count[1]), .A1 (n_155), .B0 (x_count[2]),
       .B1 (n_154), .Y (n_150));
  XNOR2X1 g3160__6417(.A (y_count[5]), .B (n_143), .Y (n_149));
  OAI2BB1X1 g3161__5477(.A0N (x_count[7]), .A1N (n_138), .B0 (n_140),
       .Y (n_148));
  DFFQXL \x_count_d_reg[8] (.CK (p_clock), .D (n_131), .Q
       (o_x_count[8]));
  DFFHQX1 \y_count_reg[2] (.CK (p_clock), .D (n_129), .Q (y_count[2]));
  SDFFQX1 \x_count_reg[1] (.CK (p_clock), .D (n_112), .SI (n_136), .SE
       (x_count[1]), .Q (x_count[1]));
  OAI32X1 g3153__2398(.A0 (y_count[3]), .A1 (n_115), .A2 (n_146), .B0
       (n_98), .B1 (n_116), .Y (n_147));
  AOI21X1 g3197__5107(.A0 (n_145), .A1 (n_200), .B0 (n_144), .Y
       (n_166));
  NOR2BX1 g3199__6260(.AN (y_count[5]), .B (n_143), .Y (n_169));
  AOI21X1 g3185__4319(.A0 (n_141), .A1 (n_174), .B0 (n_114), .Y
       (n_142));
  OAI2BB1X1 g3183__8428(.A0N (n_35), .A1N (n_125), .B0 (o_x_count[6]),
       .Y (n_140));
  OAI2BB1X1 g3181__5526(.A0N (x_count[8]), .A1N (n_138), .B0 (n_102),
       .Y (n_139));
  OAI21X1 g3203__6783(.A0 (n_44), .A1 (n_136), .B0 (x_count[2]), .Y
       (n_137));
  NAND2X1 g3206__3680(.A (x_count[5]), .B (n_124), .Y (n_135));
  OAI21X1 g3205__1617(.A0 (n_46), .A1 (n_136), .B0 (x_count[4]), .Y
       (n_134));
  NAND2X1 g3204__2802(.A (x_count[3]), .B (n_120), .Y (n_133));
  DFFQXL \y_count_d_reg[7] (.CK (p_clock), .D (n_96), .Q
       (o_y_count[7]));
  DFFQXL \pixel_data_reg[3] (.CK (p_clock), .D (n_107), .Q
       (pixel_data[3]));
  DFFQXL \y_count_d_reg[1] (.CK (p_clock), .D (n_87), .Q
       (o_y_count[1]));
  DFFQXL \pixel_data_reg[2] (.CK (p_clock), .D (n_109), .Q
       (pixel_data[2]));
  DFFQXL \pixel_data_reg[4] (.CK (p_clock), .D (n_108), .Q
       (pixel_data[4]));
  DFFQXL \pixel_data_reg[5] (.CK (p_clock), .D (n_111), .Q
       (pixel_data[5]));
  DFFQXL \pixel_data_reg[6] (.CK (p_clock), .D (n_97), .Q
       (pixel_data[6]));
  DFFQXL \pixel_data_reg[7] (.CK (p_clock), .D (n_101), .Q
       (pixel_data[7]));
  DFFQXL \y_count_d_reg[0] (.CK (p_clock), .D (n_103), .Q
       (o_y_count[0]));
  DFFQXL \pixel_data_reg[10] (.CK (p_clock), .D (n_90), .Q
       (pixel_data[10]));
  DFFQXL \pixel_data_reg[1] (.CK (p_clock), .D (n_104), .Q
       (pixel_data[1]));
  DFFQXL \y_count_d_reg[3] (.CK (p_clock), .D (n_94), .Q
       (o_y_count[3]));
  DFFQXL \y_count_d_reg[4] (.CK (p_clock), .D (n_92), .Q
       (o_y_count[4]));
  DFFQXL \y_count_d_reg[5] (.CK (p_clock), .D (n_91), .Q
       (o_y_count[5]));
  DFFQXL \pixel_data_reg[12] (.CK (p_clock), .D (n_86), .Q
       (pixel_data[12]));
  DFFQXL \y_count_d_reg[6] (.CK (p_clock), .D (n_88), .Q
       (o_y_count[6]));
  OAI31X1 g3184__5122(.A0 (n_130), .A1 (n_14), .A2 (n_100), .B0 (n_82),
       .Y (n_131));
  DFFQXL pixel_valid_reg(.CK (p_clock), .D (n_154), .Q (pixel_valid));
  OAI32X1 g3187__8246(.A0 (y_count[2]), .A1 (n_77), .A2 (n_146), .B0
       (n_43), .B1 (n_78), .Y (n_129));
  DFFQXL \pixel_data_reg[11] (.CK (p_clock), .D (n_89), .Q
       (pixel_data[11]));
  DFFQXL \pixel_data_reg[13] (.CK (p_clock), .D (n_85), .Q
       (pixel_data[13]));
  DFFQXL \pixel_data_reg[8] (.CK (p_clock), .D (n_105), .Q
       (pixel_data[8]));
  DFFQXL \pixel_data_reg[15] (.CK (p_clock), .D (n_83), .Q
       (pixel_data[15]));
  DFFQXL \pixel_data_reg[14] (.CK (p_clock), .D (n_84), .Q
       (pixel_data[14]));
  OAI211X1 g3237__7098(.A0 (x_count[6]), .A1 (n_128), .B0 (n_121), .C0
       (n_117), .Y (n_144));
  DFFQXL \pixel_data_reg[9] (.CK (p_clock), .D (n_93), .Q
       (pixel_data[9]));
  DFFQXL \pixel_data_reg[0] (.CK (p_clock), .D (n_106), .Q
       (pixel_data[0]));
  INVXL g3285(.A (n_127), .Y (n_161));
  OR2XL g3217__6131(.A (n_126), .B (n_141), .Y (n_143));
  DFFQXL \y_count_d_reg[2] (.CK (p_clock), .D (n_95), .Q
       (o_y_count[2]));
  DFFHQX1 \y_count_reg[1] (.CK (p_clock), .D (n_80), .Q (y_count[1]));
  DFFHQX1 \y_count_reg[0] (.CK (p_clock), .D (n_110), .Q (y_count[0]));
  OAI2BB1X1 g3238__1881(.A0N (n_36), .A1N (n_99), .B0 (n_125), .Y
       (n_155));
  OAI2BB1X1 g3245__5115(.A0N (n_123), .A1N (n_200), .B0 (n_121), .Y
       (n_124));
  OAI2BB1X1 g3246__7482(.A0N (n_119), .A1N (n_200), .B0 (n_121), .Y
       (n_120));
  AOI21X1 g3236__6161(.A0 (n_115), .A1 (n_174), .B0 (n_114), .Y
       (n_116));
  NAND3BXL g3288__9315(.AN (n_113), .B (x_count[6]), .C (n_112), .Y
       (n_127));
  DFFHQX1 \x_count_reg[0] (.CK (p_clock), .D (n_79), .Q (x_count[0]));
  NOR2X1 g3215__9945(.A (rst), .B (n_60), .Y (n_111));
  OAI32X1 g3243__2883(.A0 (n_38), .A1 (y_count[0]), .A2 (n_146), .B0
       (n_25), .B1 (n_39), .Y (n_110));
  NOR2X1 g3214__2346(.A (rst), .B (n_58), .Y (n_109));
  NOR2X1 g3213__1666(.A (rst), .B (n_62), .Y (n_108));
  NOR2X1 g3212__7410(.A (rst), .B (n_74), .Y (n_107));
  NOR2X1 g3201__6417(.A (rst), .B (n_73), .Y (n_106));
  NOR2X1 g3202__5477(.A (rst), .B (n_61), .Y (n_105));
  NOR2X1 g3211__2398(.A (rst), .B (n_63), .Y (n_104));
  NOR2X1 g3208__5107(.A (rst), .B (n_67), .Y (n_103));
  OAI2BB1X1 g3209__6260(.A0N (n_37), .A1N (n_81), .B0 (o_x_count[7]),
       .Y (n_102));
  NOR2X1 g3210__4319(.A (rst), .B (n_66), .Y (n_101));
  NOR2X1 g3281__8428(.A (x_count[9]), .B (n_100), .Y (n_138));
  AOI31X1 g3250__5526(.A0 (x_count[9]), .A1 (x_count[8]), .A2 (n_99),
       .B0 (n_47), .Y (n_125));
  INVX1 g3280(.A (n_121), .Y (n_136));
  OR2X1 g3258__6783(.A (n_98), .B (n_115), .Y (n_141));
  NOR2X1 g3289__3680(.A (n_27), .B (n_100), .Y (n_154));
  NOR2X1 g3216__1617(.A (rst), .B (n_65), .Y (n_97));
  NOR2X1 g3220__2802(.A (rst), .B (n_53), .Y (n_96));
  NOR2X1 g3221__1705(.A (rst), .B (n_68), .Y (n_95));
  NOR2X1 g3222__5122(.A (rst), .B (n_69), .Y (n_94));
  NOR2X1 g3223__8246(.A (rst), .B (n_70), .Y (n_93));
  NOR2X1 g3224__7098(.A (rst), .B (n_57), .Y (n_92));
  NOR2X1 g3225__6131(.A (rst), .B (n_56), .Y (n_91));
  NOR2X1 g3226__1881(.A (rst), .B (n_49), .Y (n_90));
  NOR2X1 g3227__5115(.A (rst), .B (n_55), .Y (n_89));
  NOR2X1 g3228__7482(.A (rst), .B (n_50), .Y (n_88));
  NOR2X1 g3229__4733(.A (rst), .B (n_48), .Y (n_87));
  NOR2X1 g3230__6161(.A (rst), .B (n_54), .Y (n_86));
  NOR2X1 g3231__9315(.A (rst), .B (n_52), .Y (n_85));
  NOR2X1 g3232__9945(.A (rst), .B (n_51), .Y (n_84));
  NOR2X1 g3233__2883(.A (rst), .B (n_64), .Y (n_83));
  OAI2BB1X1 g3234__2346(.A0N (n_32), .A1N (n_81), .B0 (o_x_count[8]),
       .Y (n_82));
  OAI32X1 g3235__1666(.A0 (y_count[1]), .A1 (n_41), .A2 (n_146), .B0
       (n_34), .B1 (n_42), .Y (n_80));
  OAI2BB1X1 g3247__7410(.A0N (x_count[0]), .A1N (n_75), .B0 (n_76), .Y
       (n_79));
  AOI21X1 g3244__6417(.A0 (n_77), .A1 (n_174), .B0 (n_114), .Y (n_78));
  NOR2BX1 g3283__5477(.AN (n_76), .B (n_75), .Y (n_121));
  AOI22X1 g3260__2398(.A0 (p_data_r2[3]), .A1 (n_72), .B0
       (pixel_data[3]), .B1 (n_71), .Y (n_74));
  AOI22X1 g3242__5107(.A0 (p_data_r2[0]), .A1 (n_72), .B0
       (pixel_data[0]), .B1 (n_71), .Y (n_73));
  AOI22X1 g3269__6260(.A0 (p_data_buf[1]), .A1 (n_72), .B0
       (pixel_data[9]), .B1 (n_71), .Y (n_70));
  AOI22X1 g3268__4319(.A0 (y_count[4]), .A1 (n_72), .B0 (o_y_count[3]),
       .B1 (n_71), .Y (n_69));
  AOI22X1 g3267__8428(.A0 (y_count[3]), .A1 (n_72), .B0 (o_y_count[2]),
       .B1 (n_71), .Y (n_68));
  AOI22X1 g3266__5526(.A0 (y_count[1]), .A1 (n_72), .B0 (o_y_count[0]),
       .B1 (n_71), .Y (n_67));
  AOI22X1 g3265__6783(.A0 (p_data_r2[7]), .A1 (n_72), .B0
       (pixel_data[7]), .B1 (n_71), .Y (n_66));
  AOI22X1 g3264__3680(.A0 (p_data_r2[6]), .A1 (n_72), .B0
       (pixel_data[6]), .B1 (n_71), .Y (n_65));
  AOI22X1 g3259__1617(.A0 (p_data_buf[7]), .A1 (n_72), .B0
       (pixel_data[15]), .B1 (n_71), .Y (n_64));
  AOI22X1 g3241__2802(.A0 (p_data_r2[1]), .A1 (n_72), .B0
       (pixel_data[1]), .B1 (n_71), .Y (n_63));
  AOI22X1 g3261__1705(.A0 (p_data_r2[4]), .A1 (n_72), .B0
       (pixel_data[4]), .B1 (n_71), .Y (n_62));
  AOI22X1 g3262__5122(.A0 (p_data_buf[0]), .A1 (n_72), .B0
       (pixel_data[8]), .B1 (n_71), .Y (n_61));
  AOI22X1 g3263__8246(.A0 (p_data_r2[5]), .A1 (n_72), .B0
       (pixel_data[5]), .B1 (n_71), .Y (n_60));
  SDFFQX1 \p_data_buf_reg[2] (.CK (p_clock), .D (p_data_r2[2]), .SI
       (p_data_buf[2]), .SE (n_59), .Q (p_data_buf[2]));
  SDFFQX1 \p_data_buf_reg[0] (.CK (p_clock), .D (p_data_r2[0]), .SI
       (p_data_buf[0]), .SE (n_59), .Q (p_data_buf[0]));
  SDFFQX1 \p_data_buf_reg[7] (.CK (p_clock), .D (p_data_r2[7]), .SI
       (p_data_buf[7]), .SE (n_59), .Q (p_data_buf[7]));
  SDFFQX1 \p_data_buf_reg[6] (.CK (p_clock), .D (p_data_r2[6]), .SI
       (p_data_buf[6]), .SE (n_59), .Q (p_data_buf[6]));
  SDFFQX1 \p_data_buf_reg[5] (.CK (p_clock), .D (p_data_r2[5]), .SI
       (p_data_buf[5]), .SE (n_59), .Q (p_data_buf[5]));
  SDFFQX1 \p_data_buf_reg[3] (.CK (p_clock), .D (p_data_r2[3]), .SI
       (p_data_buf[3]), .SE (n_59), .Q (p_data_buf[3]));
  AOI22X1 g3279__7098(.A0 (p_data_r2[2]), .A1 (n_72), .B0
       (pixel_data[2]), .B1 (n_71), .Y (n_58));
  AOI22X1 g3271__6131(.A0 (y_count[5]), .A1 (n_72), .B0 (o_y_count[4]),
       .B1 (n_71), .Y (n_57));
  AOI22X1 g3272__1881(.A0 (y_count[6]), .A1 (n_72), .B0 (o_y_count[5]),
       .B1 (n_71), .Y (n_56));
  AOI22X1 g3273__5115(.A0 (p_data_buf[3]), .A1 (n_72), .B0
       (pixel_data[11]), .B1 (n_71), .Y (n_55));
  AOI22X1 g3274__7482(.A0 (p_data_buf[4]), .A1 (n_72), .B0
       (pixel_data[12]), .B1 (n_71), .Y (n_54));
  AOI22X1 g3275__4733(.A0 (y_count[8]), .A1 (n_72), .B0 (o_y_count[7]),
       .B1 (n_71), .Y (n_53));
  AOI22X1 g3276__6161(.A0 (p_data_buf[5]), .A1 (n_72), .B0
       (pixel_data[13]), .B1 (n_71), .Y (n_52));
  AOI22X1 g3277__9315(.A0 (p_data_buf[6]), .A1 (n_72), .B0
       (pixel_data[14]), .B1 (n_71), .Y (n_51));
  AOI22X1 g3278__9945(.A0 (y_count[7]), .A1 (n_72), .B0 (o_y_count[6]),
       .B1 (n_71), .Y (n_50));
  AOI22X1 g3270__2883(.A0 (p_data_buf[2]), .A1 (n_72), .B0
       (pixel_data[10]), .B1 (n_71), .Y (n_49));
  AOI22X1 g3240__2346(.A0 (y_count[2]), .A1 (n_72), .B0 (o_y_count[1]),
       .B1 (n_71), .Y (n_48));
  INVX1 g3284(.A (n_81), .Y (n_47));
  NOR2BX1 g3301__1666(.AN (n_45), .B (n_128), .Y (n_46));
  NOR2X1 g3291__7410(.A (x_count[1]), .B (n_128), .Y (n_44));
  SDFFQX1 \p_data_buf_reg[4] (.CK (p_clock), .D (p_data_r2[4]), .SI
       (p_data_buf[4]), .SE (n_59), .Q (p_data_buf[4]));
  SDFFQX1 \p_data_buf_reg[1] (.CK (p_clock), .D (p_data_r2[1]), .SI
       (p_data_buf[1]), .SE (n_59), .Q (p_data_buf[1]));
  INVX1 g3290(.A (n_163), .Y (n_112));
  OR2X1 g3282__6417(.A (n_43), .B (n_77), .Y (n_115));
  OR2X1 g3294__5477(.A (n_40), .B (n_128), .Y (n_100));
  AOI21X1 g3286__2398(.A0 (n_41), .A1 (n_174), .B0 (n_114), .Y (n_42));
  AOI22X1 g3287__5107(.A0 (n_40), .A1 (n_99), .B0 (vsync_r2), .B1
       (n_2), .Y (n_81));
  DFFHQX1 pixel_flag_reg(.CK (p_clock), .D (n_31), .Q (pixel_flag));
  AOI21X1 g3300__6260(.A0 (n_38), .A1 (n_174), .B0 (n_114), .Y (n_39));
  NAND2BX1 g3293__4319(.AN (x_count[0]), .B (n_200), .Y (n_76));
  NAND2X1 g3304__8428(.A (n_113), .B (n_200), .Y (n_117));
  NAND2X1 g3296__5526(.A (x_count[0]), .B (n_200), .Y (n_163));
  OAI21X1 g3299__6783(.A0 (x_count[8]), .A1 (n_36), .B0 (n_99), .Y
       (n_37));
  OAI2BB1X1 g3302__3680(.A0N (pixel_flag), .A1N (n_145), .B0 (n_99), .Y
       (n_35));
  DFFHQX1 frame_done_reg(.CK (p_clock), .D (n_29), .Q (frame_done));
  OR2X1 g3295__1617(.A (n_34), .B (n_41), .Y (n_77));
  OAI2BB1X1 g3303__2802(.A0N (pixel_flag), .A1N (n_130), .B0 (n_99), .Y
       (n_32));
  NOR3BX1 g3305__1705(.AN (n_38), .B (pixel_flag), .C (n_182), .Y
       (n_75));
  INVX1 g3308(.A (n_200), .Y (n_128));
  NOR2X1 g3311__5122(.A (n_30), .B (n_182), .Y (n_114));
  INVX1 g3298(.A (n_72), .Y (n_71));
  INVX1 g3313(.A (n_59), .Y (n_31));
  NAND2BX1 g3309__7098(.AN (n_38), .B (y_count[0]), .Y (n_41));
  NAND2X1 g3310__6131(.A (n_30), .B (n_174), .Y (n_146));
  AND2X1 g3306__1881(.A (pixel_flag), .B (n_28), .Y (n_72));
  NOR2X1 g3314__5115(.A (rst), .B (n_174), .Y (n_29));
  NOR2BX1 g3316__7482(.AN (n_38), .B (rst), .Y (n_99));
  NAND2X1 g3317__4733(.A (n_26), .B (n_174), .Y (n_59));
  INVX1 g3318(.A (n_174), .Y (n_182));
  NOR3X1 g3315__6161(.A (vsync_r2), .B (n_27), .C (n_40), .Y (n_28));
  NAND2BX1 g3319__9315(.AN (href_r2), .B (href_r1), .Y (n_38));
  NOR2BX1 g3321__9945(.AN (href_r2), .B (pixel_flag), .Y (n_26));
  NOR2X1 g3320__2883(.A (vsync_r2), .B (rst), .Y (n_174));
  DFFQXL href_r2_reg(.CK (p_clock), .D (n_17), .Q (href_r2));
  DFFQXL \p_data_r2_reg[0] (.CK (p_clock), .D (n_16), .Q
       (p_data_r2[0]));
  DFFQXL \p_data_r2_reg[7] (.CK (p_clock), .D (n_24), .Q
       (p_data_r2[7]));
  DFFQXL \p_data_r2_reg[2] (.CK (p_clock), .D (n_15), .Q
       (p_data_r2[2]));
  DFFQXL \p_data_r2_reg[4] (.CK (p_clock), .D (n_19), .Q
       (p_data_r2[4]));
  DFFQXL \p_data_r2_reg[3] (.CK (p_clock), .D (n_21), .Q
       (p_data_r2[3]));
  DFFQXL \p_data_r2_reg[5] (.CK (p_clock), .D (n_23), .Q
       (p_data_r2[5]));
  DFFQXL \p_data_r2_reg[6] (.CK (p_clock), .D (n_22), .Q
       (p_data_r2[6]));
  DFFQXL \p_data_r2_reg[1] (.CK (p_clock), .D (n_20), .Q
       (p_data_r2[1]));
  DFFQXL vsync_r2_reg(.CK (p_clock), .D (n_18), .Q (vsync_r2));
  NAND2BX1 g3332__2346(.AN (n_123), .B (x_count[5]), .Y (n_113));
  NAND3BXL g3322__1666(.AN (x_count[0]), .B (n_25), .C (n_30), .Y
       (n_40));
  NOR2BX1 g3336__7410(.AN (p_data_r1[7]), .B (rst), .Y (n_24));
  NOR2BX1 g3335__6417(.AN (p_data_r1[5]), .B (rst), .Y (n_23));
  NOR2BX1 g3334__5477(.AN (p_data_r1[6]), .B (rst), .Y (n_22));
  NOR2BX1 g3337__2398(.AN (p_data_r1[3]), .B (rst), .Y (n_21));
  NOR2BX1 g3338__5107(.AN (p_data_r1[1]), .B (rst), .Y (n_20));
  NOR2BX1 g3344__6260(.AN (p_data_r1[4]), .B (rst), .Y (n_19));
  NOR2BX1 g3343__4319(.AN (vsync_r1), .B (rst), .Y (n_18));
  NOR2BX1 g3342__8428(.AN (href_r1), .B (rst), .Y (n_17));
  NOR2BX1 g3341__5526(.AN (p_data_r1[0]), .B (rst), .Y (n_16));
  NOR2BX1 g3340__6783(.AN (p_data_r1[2]), .B (rst), .Y (n_15));
  NAND2BX1 g3339__3680(.AN (n_45), .B (x_count[4]), .Y (n_123));
  AND2X1 g3356__1617(.A (n_14), .B (x_count[9]), .Y (n_27));
  DFFQXL \p_data_r1_reg[6] (.CK (p_clock), .D (n_11), .Q
       (p_data_r1[6]));
  DFFQXL \p_data_r1_reg[0] (.CK (p_clock), .D (n_5), .Q (p_data_r1[0]));
  DFFQXL vsync_r1_reg(.CK (p_clock), .D (n_10), .Q (vsync_r1));
  DFFQXL href_r1_reg(.CK (p_clock), .D (n_12), .Q (href_r1));
  NAND2BX1 g3358__2802(.AN (n_119), .B (x_count[3]), .Y (n_45));
  NAND3BXL g3345__1705(.AN (n_170), .B (y_count[5]), .C (y_count[6]),
       .Y (n_30));
  DFFQXL \p_data_r1_reg[1] (.CK (p_clock), .D (n_6), .Q (p_data_r1[1]));
  DFFQXL \p_data_r1_reg[3] (.CK (p_clock), .D (n_9), .Q (p_data_r1[3]));
  DFFQXL \p_data_r1_reg[4] (.CK (p_clock), .D (n_3), .Q (p_data_r1[4]));
  DFFQXL \p_data_r1_reg[2] (.CK (p_clock), .D (n_8), .Q (p_data_r1[2]));
  DFFQXL \p_data_r1_reg[5] (.CK (p_clock), .D (n_4), .Q (p_data_r1[5]));
  DFFQXL \p_data_r1_reg[7] (.CK (p_clock), .D (n_7), .Q (p_data_r1[7]));
  OAI21X1 g3357__5122(.A0 (n_145), .A1 (n_130), .B0 (pixel_flag), .Y
       (n_36));
  NAND2X1 g3364__8246(.A (n_13), .B (n_145), .Y (n_14));
  NOR2BX1 g3365__7098(.AN (href), .B (rst), .Y (n_12));
  NOR2BX1 g3367__6131(.AN (p_data[6]), .B (rst), .Y (n_11));
  NOR2BX1 g3369__1881(.AN (vsync), .B (rst), .Y (n_10));
  NOR2BX1 g3360__5115(.AN (p_data[3]), .B (rst), .Y (n_9));
  NOR2BX1 g3359__7482(.AN (p_data[2]), .B (rst), .Y (n_8));
  NAND2X1 g3370__4733(.A (x_count[2]), .B (x_count[1]), .Y (n_119));
  NOR2BX1 g3361__6161(.AN (p_data[7]), .B (rst), .Y (n_7));
  NOR2BX1 g3362__9315(.AN (p_data[1]), .B (rst), .Y (n_6));
  NOR2BX1 g3363__9945(.AN (p_data[0]), .B (rst), .Y (n_5));
  NOR2BX1 g3366__2883(.AN (p_data[5]), .B (rst), .Y (n_4));
  NOR2BX1 g3368__2346(.AN (p_data[4]), .B (rst), .Y (n_3));
  NAND2X1 g3371__1666(.A (y_count[8]), .B (y_count[7]), .Y (n_170));
  INVX1 g3372(.A (y_count[2]), .Y (n_43));
  INVX1 g3373(.A (y_count[1]), .Y (n_34));
  INVX1 g3374(.A (y_count[3]), .Y (n_98));
  INVX1 g3376(.A (x_count[8]), .Y (n_13));
  INVX1 g3377(.A (x_count[9]), .Y (n_130));
  INVX1 g3379(.A (rst), .Y (n_2));
  INVX1 g3382(.A (x_count[1]), .Y (n_0));
  INVX1 g3381(.A (y_count[0]), .Y (n_25));
  INVX1 g3380(.A (y_count[4]), .Y (n_126));
  INVX1 g3378(.A (x_count[7]), .Y (n_145));
  AO21XL g2(.A0 (n_149), .A1 (n_174), .B0 (n_114), .Y (n_199));
  NOR2BX1 g3466(.AN (pixel_flag), .B (n_182), .Y (n_200));
  OAI2BB1X1 g3467(.A0N (n_117), .A1N (n_121), .B0 (x_count[6]), .Y
       (n_201));
endmodule

